base:
  title: "tobeg"
  url: "http://baidu.com"
  favicon: "favicon.png"
  toSells:
    - "瞧一瞧、看一看、这里来个穷要饭哎"
    - "大娘好，大爷善，可怜可怜俺这个穷光蛋"
    - "给个馍，给口汤，祝恁长命又健康"
    - "人家给，你不给，人家比你长得美"
    - "人家掏，你不掏，人家比你尿类高"
    - "让我走，我就走，老板伸出富贵手"
    - "这二年，我没来，老板已经发大财"
    - "一元两元不算少，给的多了也不要"

alipay:
  appid: ""
  private_key: ""
  public_content_rsa2: ""
  app_public_content: ""

server:
  port: 10020
