base:
  name: "tobeg"
  url: "http://baidu.com"
  toSells:
    - "瞧一瞧、看一看、这里来个穷要饭哎"
    - "大娘好，大爷善，可怜可怜俺这个穷光蛋"
    - "给个摸，给口汤，祝恁长命又健康"
    - "行行好，行行秒，施舍的人呱呱叫"

alipay:
  appid: ""
  private_key: ""
  public_content_rsa2: ""
  app_public_content: ""

server:
  port: 10020
